export const MISS_CATEGORIES = [
  {
    id: 'visual-discipline',
    name: 'Visual Discipline',
    short: 'Visual',
    desc: 'Eyes left the target',
    cue: 'See it longer before move',
    icon: 'eye-outline',
    colorBg: 'rgba(239, 68, 68, 0.2)',
    colorBorder: 'rgba(239, 68, 68, 0.4)',
    accent: '#F87171',
    videoTitle: 'Locking Your Eyes to the Target',
    drillTitle: 'Late Look Drill',
  },
  {
    id: 'timing-breakdown',
    name: 'Timing Breakdown',
    short: 'Timing',
    desc: 'Trigger pulled too early or late',
    cue: 'Match gun speed to target',
    icon: 'timer-outline',
    colorBg: 'rgba(249, 115, 22, 0.2)',
    colorBorder: 'rgba(249, 115, 22, 0.4)',
    accent: '#FB923C',
    videoTitle: 'When to Be Aggressive vs Deliberate',
    drillTitle: 'Late Trigger Correction',
  },
  {
    id: 'speed-mismatch',
    name: 'Speed Mismatch',
    short: 'Speed',
    desc: "Gun speed didn't match target",
    cue: 'Move with the bird, not at it',
    icon: 'speedometer-outline',
    colorBg: 'rgba(234, 179, 8, 0.2)',
    colorBorder: 'rgba(234, 179, 8, 0.4)',
    accent: '#FACC15',
    videoTitle: 'Matching Gun Speed to Target Speed',
    drillTitle: 'Fast Crosser Control',
  },
  {
    id: 'target-line-misread',
    name: 'Target Line Misread',
    short: 'Line',
    desc: 'Wrong line of sight on target',
    cue: 'Read the line at the break point',
    icon: 'locate-outline',
    colorBg: 'rgba(59, 130, 246, 0.2)',
    colorBorder: 'rgba(59, 130, 246, 0.4)',
    accent: '#60A5FA',
    videoTitle: 'Reading the Target Line',
    drillTitle: 'Line Tracing Drill',
  },
  {
    id: 'pressure-seq-breakdown',
    name: 'Pressure / Seq Breakdown',
    short: 'Pressure',
    desc: 'Routine collapsed under pressure',
    cue: 'Reset, breathe, restart sequence',
    icon: 'pulse-outline',
    colorBg: 'rgba(168, 85, 247, 0.2)',
    colorBorder: 'rgba(168, 85, 247, 0.4)',
    accent: '#C084FC',
    videoTitle: 'Holding Routine Under Pressure',
    drillTitle: 'Pressure Reset Drill',
  },
  {
    id: 'planning-error',
    name: 'Planning Error',
    short: 'Planning',
    desc: 'Wrong hold, foot, or break point',
    cue: 'Plan break point first, then mount',
    icon: 'bulb-outline',
    colorBg: 'rgba(16, 185, 129, 0.2)',
    colorBorder: 'rgba(16, 185, 129, 0.4)',
    accent: '#34D399',
    videoTitle: 'Pre-Shot Planning Fundamentals',
    drillTitle: 'Hold Point Setup Drill',
  },
];

export const getMissCategory = id =>
  MISS_CATEGORIES.find(c => c.id === id) || null;
